### ISSUE TITLE
Need to review archive of Data citations and dataset info in eLife XML to see whether would convert to relation

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#103]

**Comment by Melissa37** [comment]
For example:

```xml
<ref id="bib34">
        <element-citation publication-type="data">
            <person-group person-group-type="author">
                <name>
                    <surname>Radoshevich</surname>
                    <given-names>L</given-names>
                </name>
                <name>
                    <surname>Impens</surname>
                    <given-names>F</given-names>
                </name>
                <name>
                    <surname>Ribet</surname>
                    <given-names>D</given-names>
                </name>
                <name>
                    <surname>Quereda</surname>
                    <given-names>JJ</given-names>
                </name>
                <name>
                    <surname>Nam Tham</surname>
                    <given-names>T</given-names>
                </name>
                <name>
                    <surname>Nahori</surname>
                    <given-names>MA</given-names>
                </name>
                <name>
                    <surname>Bierne</surname>
                    <given-names>H</given-names>
                </name>
                <name>
                    <surname>Dussurget</surname>
                    <given-names>O</given-names>
                </name>
                <name>
                    <surname>Pizarro-Cerdá</surname>
                    <given-names>J</given-names>
                </name>
                <name>
                    <surname>Knobeloch</surname>
                    <given-names>KP</given-names>
                </name>
                <name>
                    <surname>Cossart</surname>
                    <given-names>P</given-names>
                </name>
            </person-group>
            <year iso-8601-date="2015">2015a</year>
            <data-title>ISG15 counteracts <italic>Listeria monocytogenes</italic>
                infection</data-title>
            <source>ProteomeXchange</source>
            <pub-id pub-id-type="archive"
                xlink:href="http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD001805"
                >PXD001805</pub-id>
        </element-citation>
    </ref>
```

Allowed identifier types in Crossref:
https://data.crossref.org/reports/help/schema_doc/4.3.7/4.3.7.html

<xsd:enumeration value="doi"/>
        <xsd:enumeration value="issn"/>
        <xsd:enumeration value="isbn"/>
        <xsd:enumeration value="uri"/>
        <xsd:enumeration value="pmid"/>
        <xsd:enumeration value="pmcid"/>
        <xsd:enumeration value="purl"/>
        <xsd:enumeration value="arxiv"/>
        <xsd:enumeration value="ark"/>
        <xsd:enumeration value="handle"/>
        <xsd:enumeration value="uuid"/>
        <xsd:enumeration value="ecli"/>
        <xsd:enumeration value="accession"/>
        <xsd:enumeration value="other"/>

**Comment by gnott** [comment]
So far the logic I have is: if the citation is ``publication-type="data"``, if it has a ``doi``, ``accession``, ``pmid`` or ``uri``, then a ``<related_item>`` is created in the Crossref deposit.

**Comment by Melissa37** [comment]
@gnott , have we ever had a data set without one of those values?

**Comment by gnott** [comment]
It has happened where a data citation does not have one of those. The list is short (below, only if any version of the article has an example). These will remain in the citation list of the Crossref deposit, and it will just not have a related_item tag added to the Crossref deposit as a result, since there is not a good identifier to use.

```
```

**Comment by Melissa37** [comment]
@elifesciences/production 

Could you investigate these references:

10.7554/eLife.14590, bib73
10.7554/eLife.15341, bib11
10.7554/eLife.17029, bib22
10.7554/eLife.17029, bib28
10.7554/eLife.20697, bib64
10.7554/eLife.20697, bib64
10.7554/eLife.20697, bib64
10.7554/eLife.21792, bib22
10.7554/eLife.21792, bib44
10.7554/eLife.22144, bib4
10.7554/eLife.23611, bib71
10.7554/eLife.26000, bib38
10.7554/eLife.26410, bib40

They are data citations without an url or ID and so should not get through the system?

@JGilbert-eLife and Alistair this is relevant to you.

Cheers
