### ISSUE TITLE
 convert <element-citation publication-type="clinicaltrial"> to something else

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#107]
OK, this could get pretty complex and I am not sure it's good enough use case for eLife, but for clinical journals (ie BMJ) it would be good I guess.

We have had 1 or 2 references that are clinical trials, here is our example XML:
```xml
 <ref id="bib41">
        <element-citation publication-type="clinicaltrial">
            <person-group person-group-type="sponsor">
                <collab>Scripps Translational Science Institute</collab>
            </person-group>
            <year iso-8601-date="2015">2015</year>
            <article-title>Scripps Wired for Health Study</article-title>
            <ext-link ext-link-type="uri" xlink:href="https://clinicaltrials.gov/ct2/show/NCT01975428">https://clinicaltrials.gov/ct2/show/NCT01975428</ext-link>
        </element-citation>
    </ref> ```
Currently converts to:
```xml
<citation key="41">
                        <author>Scripps Translational Science Institute</author>
                        <cYear>2015</cYear>
                        <article_title>Scripps Wired for Health Study</article_title>
                    </citation>
```
Crossref have done a fair amount of work on Clinical trials (I was on their working group for this).
We should convert to:

```<xml>
<program xmlns="http://www.crossref.org/clinicaltrials.xsd">
<clinical-trial-number registry="10.18810/clinical-trials-gov" >NCT01975428</clinical-trial-number>
```
I used the Crossref schema for clinical trials (available via API: http://api.crossref.org/works/10.18810/registries/transform/application/vnd.crossref.unixsd+xml) to figure out the ID of the registry. However, I don't know whether that can be done progrematically?

**Comment by Melissa37** [comment]
Pend this issue until output from JATS4R Clinical trial subgroup

**Comment by gnott** [comment]
Is there a way the clinical trial registry value could be included in the JATS XML itself, or would that not be possible?

I suppose the document you linked above with the list of registries would be able to match the particular clinical trial registry to the trial number via the regular expression matches it specifies. This seems like more work and possibly error prone. 

Do you know if the list is updated often, or would we be able to turn it into a function encapsulated in the code that translates trial numbers to the correct clinical trial registry?

**Comment by Melissa37** [comment]
Hi there
I am going to close this ticket - The JATS4R recommendation will be that clinical trials are never allowed as references, so we should not be doing this!
It's been blocked now via Schematron for further publications.
