### ISSUE TITLE
citation @key unique numbers - numerical to elife JATS XML or Crossref XML

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#108]
Now we'll be potentially removing some references and changing them to something else, ie data and clinical trial, do we renumber the unique keys when skipping one of them, or retain the same number as the JATS ref @id?
As Crossref just need a unique key, for human readability and troubleshooting, I think I'd prefer that the crossref key matches the ref id and so if pne is pulled out of the citation list and converted to something else, it just skips that number in the crossref deposit. Make sense?

Also, I am still slightly confused about unstructured_citation> and whether these also get a unique key or not. 
Needs testing or asking Crossref (but I'm asking them so much right now!)

**Comment by gnott** [comment]
Each Crossref citation as part of a deposit will have a unique number and still be in the original order listed in the article, e.g.

```
<citation key="32">
<volume_title>United States patent</volume_title>
<cYear>2011</cYear>
<article_title>IRE-1alpha inhibitors</article_title>
<unstructured_citation>
Patterson JB, Lonergan DG, Flynn GA, Qingpeng Z, Pallai PV, Mankind Corp. 2011. IRE-1alpha inhibitors. United States patent. US20100941530. http://europepmc.org/patents/PAT/US2011065162.
</unstructured_citation>
</citation>
```

(still waiting to hear whether non-unstuctured_citation tags are allowed or encouraged to be included along side).

There may not be the same unique identifiers included for each citation, such as a DOI, depending on the format of the citation.

I will assign to you @Melissa37 if you are able to answer the original question.

**Comment by Melissa37** [comment]
Makes total sense to keep our same unique and unstructured citations have a unique key too.
So, it will just be items that are pulled out as relationship-types (data) that will be different then.

**Comment by Melissa37** [comment]
On call with Graham - code takes the ID from the JATS XML rather than creating a list for Crossref. Therefore reusable so other publishers could retain their tagging style

**Comment by gnott** [comment]
I was incorrect about that, it is incrementing an integer value for each citation when generating the Crossref deposit.

The todo here will be to use the id of the citation from the XML file as the id of the Citation in the Crossref deposit.
