### ISSUE TITLE
Crossref to provide <elocation-id> element in their DTD

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#110]
This has been an issue I have had open with them for 3 years.
They tell me it will be fixed within the week

**Comment by gnott** [comment]
Do you mean the ``elocation-id`` of the article itself, or of citations?

I added support for article elocation-id in the new code base after looking at non-eLife samples. I turned it off for eLife in the settings. An example of output is

```
<publisher_item>
<item_number item_number_type="article_number">3</item_number>
<identifier id_type="doi">10.5334/cstp.77</identifier>
</publisher_item>
```

**Comment by Melissa37** [comment]
![screen shot 2017-08-08 at 16 42 11](https://user-images.githubusercontent.com/6051876/29080833-c3a4528c-7c58-11e7-9f74-d4eccc0de9a9.png)

**Comment by Melissa37** [comment]
Yeaaaahhhhy, at last!!

**Comment by gnott** [comment]
I'm thinking this is not available just yet, it may become available in schema 4.4.0; http://data.crossref.org/schemas/common4.4.0.xsd current has it commented out:

```
<!--
  unomment when cs3391 is complete
			<xsd:element ref="elocation_id" minOccurs="0"/>
-->
```

**Comment by Melissa37** [comment]
I have chased them up! This is so annoying :-(

**Comment by Melissa37** [comment]
@gnott Do you mean the elocation-id of the article itself? **Yes**

**Comment by Melissa37** [comment]
related to https://github.com/elifesciences/elife-crossref-feed/issues/112#issue

**Comment by Melissa37** [comment]
From Crossref:
Sorry for the delay and confusion - our technical team had agreed that we would deploy the schema change prior to making changes to the citation matching code, but reversed the decision (while I was on vacation! argh).  The schema was edited but they neglected to remove the note from the update log (at the top of the schema).

We're also in discussion about calling the field elocation-id vs. elocation_id as while there are some inconsistencies our schema generally uses underscores instead of - in element names. I'm trying to move this along, I'll keep you updated.

**Comment by fgnievinski** [comment]
related issue: #134
