### ISSUE TITLE
Where can MathMl be supported in Crossref schema

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#111]

**Comment by gnott** [comment]
I have a question about mathml in abstracts. 

Recently in order to support PubMed deposits, the mathml is added back when parsing the abstract to flow through to the next step.

As I was testing the Crossref deposits using the latest libraries, it includes some marked up mathml in the abstract.

I cannot find a specific article in the Crossref help section specifically about mathml in abstracts. There is an article about mathml support for title tags: https://support.crossref.org/hc/en-us/articles/213083726-Including-MathML-in-deposits

Some options are:
a) leave the mathml in abstracts with the tagging around them, which may show up as mathml tags when people query the Crossref metadata
b) add the ``mml`` name space to abstracts, but I don't know if Crossref supports them in abstracts (as they do in title tags)
c) replace the mathml with some placeholder, as is suggested in Pubmed deposits, like `` [Formula: see text]``

Would you have any comments on this @Melissa37?

**Comment by Melissa37** [comment]
From the crossref site: 

Abstracts: publishers using JATS may include their JATS-formatted abstracts in deposits

NLM/JATS abstracts

Abstracts imported from JATS-formatted XML may be included in Crossref deposits. A namespace prefix (jats:) must be used for the abstract and all child elements, and the namespace must be included in the schema declaration. Multiple abstracts may be included.

Schema declaration:

<doi_batch version="4.3.6" xmlns="http://www.crossref.org/schema/4.3.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xsi:schemaLocation="http://www.crossref.org/schema/4.3.6 http://www.crossref.org/schemas/crossref4.3.6.xsd" xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1"​>

Example:

. . . 
</person_name>
</contributors> 
<jats:abstract><jats:p>We describe a method for cloning nucleic acid molecules onto the surfaces of 5-&#x03BC;m microbeads rather than in biological hosts. A unique tag sequence is attached to each molecule, and the tagged library is amplified. Unique tagging of the molecules is achieved by sampling a small fraction (1&#x0025;) of a very large repertoire of tag sequences. The resulting library is hybridized to microbeads that each carry &#x2248;10<jats:sup>6<jats:/sup> strands complementary to one of the tags. About 10<jats:sup>5<jats:/sup> copies of each molecule are collected on each microbead. Because such clones are segregated on microbeads, they can be operated on simultaneously and then assayed separately. To demonstrate the utility of this approach, we show how to label and extract microbeads bearing clones differentially expressed between two libraries by using a fluorescence-activated cell sorter (FACS). Because no prior information about the cloned molecules is required, this process is obviously useful where sequence databases are incomplete or nonexistent. More importantly, the process also permits the isolation of clones that are expressed only in given tissues or that are differentially expressed between normal and diseased states. Such clones then may be spotted on much more cost-effective, tissue- or disease-directed, low-density planar microarrays.</jats:p>
</jats:abstract>
<publication_date media_type="print"> 
<year>2000</year>
</publication_date>
. . .

As every tag requires the jats: prefix, I think we need to ask the specific question re mathml. I will raise a query with them.

Cheers

**Comment by Melissa37** [comment]
However, just found this:

Including MathML in deposits

Beginning with schema version 4.3.2, MathML may be included in the title, subtitle, and original_language_title elements. The MathML namespace (mml) must be defined in the schema declaration, for example:

<doi_batch version="4.3.2" xmlns="http://www.crossref.org/schema/4.3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.crossref.org/schema/4.3.2 http://www.crossref.org/schemas/crossref4.3.2.xsd" xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xmlns:mml="http://www.w3.org/1998/Math/MathML"​>

Note that all MathML markup must include a mml namespace prefix:

<journal_article publication_type="full_text">
<titles>
<title>Selectron production at an <mml:math><mml:msup><mml:mi>e</mml:mi><mml:mo>&#x02212;</mml:mo></mml:msup><mml:msup><mml:mi>e</mml:mi><mml:mo>&#x02212;</mml:mo></mml:msup></mml:math> linear collider with transversely polarized beams</title>
</titles>

Will still ask them

**Comment by Melissa37** [comment]
We support MathML in JATS abstracts as of schema version 4.3.5.  The MathML elements should use a MathML namespace prefix (such as mml) and the namespace needs to be declared. I've included an example abstract below and I'll update our documentation to be more clear on this:

```
xml
<jats:abstract><jats:p>Acute and chronic lung inflammation is associated with numerous important disease pathologies including asthma, chronic obstructive pulmonary disease and silicosis. Lung fibroblasts are a novel and important target of anti-inflammatory therapy, as they orchestrate, respond to, and amplify inflammatory cascades and are the key cell in the pathogenesis of lung fibrosis. Peroxisome proliferator-activated receptor gamma (PPAR<mml:math><mml:mi>γ</mml:mi></mml:math>) ligands are small molecules that induce anti-inflammatory responses in a variety of tissues. Here, we report for the first time that PPAR<mml:math><mml:mi>γ</mml:mi></mml:math> ligands have potent anti-inflammatory effects on human lung fibroblasts. 2-cyano-3, 12-dioxoolean-1, 9-dien-28-oic acid (CDDO) and 15-deoxy-<mml:math><mml:msup><mml:mi>Δ</mml:mi><mml:mrow><mml:mn>12</mml:mn><mml:mo>,</mml:mo><mml:mn>14</mml:mn></mml:mrow></mml:msup></mml:math>-prostaglandin J<jats:sub>2</jats:sub> (15d-PGJ<jats:sub>2</jats:sub>) inhibit production of the inflammatory mediators interleukin-6 (IL-6), monocyte chemoattractant protein-1 (MCP-1), COX-2, and prostaglandin (PG)E<jats:sub>2</jats:sub> in primary human lung fibroblasts stimulated with either IL-1<mml:math><mml:mi>β</mml:mi></mml:math> or silica. The anti-inflammatory properties of these molecules are not blocked by the PPAR<mml:math><mml:mi>γ</mml:mi></mml:math> antagonist GW9662 and thus are largely PPAR<mml:math><mml:mi>γ</mml:mi></mml:math> independent. However, they are dependent on the presence of an electrophilic carbon. CDDO and 15d-PGJ<jats:sub>2</jats:sub>, but not rosiglitazone, inhibited NF-<mml:math><mml:mi>κ</mml:mi></mml:math>B activity. These results demonstrate that CDDO and 15d-PGJ<jats:sub>2</jats:sub> are potent attenuators of proinflammatory responses in lung fibroblasts and suggest that these molecules should be explored as the basis for novel, targeted anti-inflammatory therapies in the lung and other organs.</jats:p></jats:abstract>
```

**Comment by gnott** [comment]
For now, I think we can go with supporting mathml in abstracts by default.

There is an option to include jats tagging for abstracts (true or false), for which the default is false and eLife uses false. This is because the extra jats tags in the abstract are hard to read.

For mathml, if you do not include the mathml tagging, then the math formula makes no sense, and is why it will be the default with no option to turn it off, for now.
