### ISSUE TITLE
<elocation-id> to be added to meta for article being deposited

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#112]

**Comment by gnott** [comment]
I'm not seeing exactly where this should go - perhaps in an ``<publisher_item><item_number>`` element with a particular ``item_number_type`` attribute of ``elocation-id``?

This is different from the citation elocation-id values.

**Comment by Melissa37** [comment]
I think this should be closed and we use https://github.com/elifesciences/elife-crossref-feed/issues/110 to discuss this issue?
