### ISSUE TITLE
Fundref identifier value

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#117]
Reviewing related_item schema details, I am looking at a document about funding data: https://support.crossref.org/hc/en-us/articles/214360746

The examples for funder_identifier include a full URL style DOI, e.g.

```
<fr:assertion name="funder_identifier">https://doi.org/10.13039/R01ZDA</fr:assertion>
```

However, up until now our generated Crossref XML just includes the identifier itself, e.g.

```
<fr:assertion name="funder_identifier">100000011</fr:assertion>
```

@Melissa37 does changing to use the full URL format seem to be the right choice? I am assuming all previous deposits were still valid that specified the identifier only, but that may not be true.

**Comment by Melissa37** [comment]
I'll send a message to Crossref to check
Thanks for finding this.
M

**Comment by kmeddings** [comment]
Hello - Crossref here! Both will work, but the full URL is preferable.

**Comment by Melissa37** [comment]
Fantastic, thanks Kirsty!
M

**Comment by gnott** [comment]
Thanks for the quick answers, I will commit a code change to use the full URL.
