### ISSUE TITLE
Converting uri to doi when possible

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#121]
Example:
```
xml
<rel:inter_work_relation identifier-type="uri" relationship-type="isSupplementedBy">http://dx.doi.org/10.5061/dryad.cv39v</rel:inter_work_relation>
```

Where possible, our code should recognise the http://dx.doi.org/ prefix and if this exists and the identifier-type="uri", change that to identifier-type="doi"

**Comment by gnott** [comment]
What I've done is set the doi attributes of the article objects if thee is a uri-like attribute at the time the data is parsed and the object are created.

In the Crossref tests, there's an example that has uri and no doi for both a dataset and a citation (both records have the same value). In the Crossref deposit it ends up as a doi whereas before it was a uri, e.g.

```
<rel:program>
<rel:related_item>
<rel:description>
Extracellular space preservation aids the connectomic analysis of neural circuits
</rel:description>
<rel:inter_work_relation identifier-type="doi" relationship-type="isSupplementedBy">10.5061/dryad.36h28</rel:inter_work_relation>
</rel:related_item>
<rel:related_item>
<rel:description>
Data from: extracellular space preservation aids the connectomic analysis of neural circuits
</rel:description>
<rel:inter_work_relation identifier-type="doi" relationship-type="references">10.5061/dryad.36h28</rel:inter_work_relation>
</rel:related_item>
</rel:program>
```
