### ISSUE TITLE
Check logic for equal contributions

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#122]
There is some logic it seems for corresponding and equal contributors, and the ``"sequence"`` attribute is set in the Crossref deposit as ``first`` or ``additional``. I want to check this logic since it seems to only set one contributor as ``first`` even if there are equal contributing authors. Otherwise, if there can be only one ``first`` author, then the logic for equal contributions is probably redundant.

**Comment by Melissa37** [comment]
Hi Graham

I agree - for crossref they are not collecting or acknowledging equal contributions and they just want the sequence of authors as seen in the paper.

M

**Comment by gnott** [comment]
There's some detail about the author sequence value of ``first`` or ``additional`` on https://support.crossref.org/hc/en-us/articles/214567746-Authors-and-editors.

It seems like you can assign ``first`` to more than one author and the deposit is still valid.

I'm not sure why the old code had some logic around whether an author was a corresponding author or if they were an equal contributor when it sets the sequence value. In any rate, the code has no effect anyway, since only one author gets a sequence of ``first`` as the logic is.

I will simplify the logic around the sequence value, and it will continue to only set one author - the first author - as ``first``.
