### ISSUE TITLE
Parser support for reference of publication-type="webpage"

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#131]
JATS citation tags (either ``<mixed-citation>`` or ``<element-citation>``) often have the attribute ``publication-type="webpage"`` for web references. In eLife XML, the name is ``publication-type="web"``. Proposed here is to support both values when converting a citation into reference JSON data of type web.

**Comment by Melissa37** [comment]
Sounds good!
JATS4R should come out with a recommendation for this soon.

M
