### ISSUE TITLE
Make default access indicators in preferences more general purpose re: applies_to="am"

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#132]
When adding access indicators from the http://www.crossref.org/AccessIndicators.xsd namespace to the Crossref deposit, in the preferences file the list of values for ``access_indicators_applies_to`` indicates to which publications the license should apply.

The default right now is

```
access_indicators_applies_to: ["vor", "am", "tdm"]
```

Adding a license for ``"am"`` (accepted manuscript) is apparently not too common. eLife does it, others do not.

For the best fit, the task proposed is to remove ``"am"`` from the default list, and add it back for the ``elife`` preferences section. eLife will continue to use the three values, as above, in their system by specifying the list just in their preferences file configuration section.

**Comment by Melissa37** [comment]
Sounds good :-)
