### ISSUE TITLE
Resupply Archive - Decision letter ID added to URL

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#136]
@thewilkybarkid 
@gnott 

Can you guys populate this ticket so we remember why and what when we get round to doing it?

**Comment by Melissa37** [comment]
https://github.com/elifesciences/issues/issues/2196#issuecomment-411120060

**Comment by gnott** [comment]
There is a function named ``elife_style_component_attributes()`` in the ``elife-crossref-xml-generation`` project to tell Crossref about the ``#decision-letter`` and ``#author-response`` anchors for the component DOIs (this specific code block https://github.com/elifesciences/elife-crossref-xml-generation/blob/develop/elifecrossref/generate.py#L368-L372).

The DOIs for these components Crossref has will be incorrect, so after all the coding is updated, we should resupply all the eLife articles to Crossref for them to pick up the updated URL anchor.

**Comment by gnott** [comment]
May be ready to do a full Crossref resupply today or tomorrow. It shouldn't have any impact on other systems (I think), except for possibly some unexpected ingest messages from Crossref.

**Comment by gnott** [comment]
Lax backfill is finished, ready for resupply of all articles to Crossref.

**Comment by gnott** [comment]
The full list of articles is re submitted now. There are a few errors, some failures on particular DOIs and one failure at an article level. @Melissa37 are these errors something we should look into further? They may be mentioned in the previous Crossref resupply we did in Oct 2017.
