### ISSUE TITLE
Create sample DL/AR XML file for Exeter

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#144]
@gnott Exeter requires this in order to quote for the work at their end. Can you do this based on what you will have done at the end?

**Comment by gnott** [comment]
The Crossref peer review deposits are mostly concerned with the metadata of the `<sub-article>`, and it doesn't really matter the actual content. Is the request for something like a kitchen sink peer review JATS? Can it come from the `00666` kitchen sink? Or is ExeterPremedia interested in seeing the actual Crossref peer review deposit XML? (example here: https://github.com/elifesciences/elife-crossref-xml-generation/blob/develop/tests/test_data/elife-crossref-peer_review-00666-20170717071707.xml)

Also, how closely does this also relate to the JATS we plan to send to a decision letter API endpoint? I hope to have a sample in a few weeks for that.

**Comment by Melissa37** [comment]
Whoops sorry, wrong repo! Not sure where to put this? Exeter premedia would like a DL/AR XML file example of what you've produced from Pandoc +/- other processes. Not to do with Crossref deposit really.

Sorry for the confusion - which repo should I attach this request to?

**Comment by gnott** [comment]
Thanks for the clarification @Melissa37! You can add it as an issue to the https://github.com/elifesciences/decision-letter-parser repo if you want, or to https://github.com/elifesciences/issues and then add it to our project board.

I am planning to generate some XML samples, hopefully from real data, in the next few weeks. I had also thought we might want to create a kitchen sink XML for decision letters to illustrate all the possible contents that may be included. That can be done later or sooner, if you think it would be useful.

**Comment by Melissa37** [comment]
Thanks, added to right place now: https://github.com/elifesciences/decision-letter-parser/issues/22
