### ISSUE TITLE
<doi_batch_id>elife01856</doi_batch_id>

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#22]
Verify how to form this

**Comment by Melissa37** [comment]
Hi Graham, this can be closed right?

**Comment by gnott** [comment]
The issue I believe is to have a unique and descriptive batch id. We've solve this by sending only 1 article per batch file, and keeping the datetime of the deposit. E.g.

elife-crossref-09214-20151117123534.xml

09214 is the article ID
20151117123534 is the date YYYYMMDDhhmmss
