### ISSUE TITLE
VoR: mime types

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#26]
TNQ: When we use the mime type as we process for HWX in Crossref XML, it throws an error message during validation. For example, mime type for "avi" is video/x-msvideo in HWX but in Crossref mime type is video/avi. Please advise how to proceed in this case.

eLife: So, CrossRef refers us to: http://www.iana.org/assignments/media-types/media-types.xhtml for the mime types. 
Do I understand you correctly that they do not use the same library as HW and so for non standard mime types this will be really hard? I think for videos I'd like them to be included, so you'll need to change the mime type reference for CrossRef deposits, but for non standard mime types for supplemental files, for example, I suggets we remove the information from the submission:
<format mime_type="XXXXX"/>

Does that sound like a good solution?

**Comment by Melissa37** [comment]
This is the list of HW supported mime-types:
https://production.highwire.org/doc/mime_types.dtl

I'll Skype or email you my credentials so you can look at this page :-)

**Comment by gnott** [comment]
Articles published up to August 7, 2015, these are all the ``mimetype/mime-subtype" used so far in ``<media>`` tags (below). 

I start with trying to choose an appropriate crossref mimetype for as many as possible. The list of mime types possible are in http://www.crossref.org/schemas/common4.3.5.xsd listed in the ``<xsd:attributeGroup name="mime_type.atts">`` element.

The mime type may be optional, so if we cannot match the mime type from JATS to the mime type in CrossRef then we should probably omit the mime type in the Crossref deposit.

The mime types used so far:

```
application/JNB
application/RData
application/csv
application/doc
application/docx
application/eps
application/fas
application/fasta
application/gz
application/m
application/mat
application/msf
application/nex
application/pdb
application/pdf
application/png
application/pptx
application/rar
application/rtf
application/tar.gz
application/tsv
application/txt
application/wrl
application/xls
application/xlsb
application/xlsx
application/zip
application/zip/zip
chemical/fasta
chemical/pdb
image/tif
plain/txt
text/R
text/cp
text/csv
text/pl
text/py
text/r
text/rtf
text/tsv
text/txt
video/3gp
video/AVI
video/MOV
video/avi
video/f4v
video/m4v
video/mov
video/mp4
video/mpeg
video/mpg
video/wmv
```

**Comment by Melissa37** [comment]
Hi there

That sounds like the best approach, to ignore it if we cannot match it.
Have you tested validation without a mime type?

**Comment by gnott** [comment]
Validation works if any mime_type is omitted. I've added some common and expected mime type conversions, and we can adjust those. Right now they're in the ``crossref_mime_type()`` function on my  dev branch, https://github.com/gnott/elife-poa-xml-generation/blob/crossref/generateCrossrefXml.py#L494

**Comment by Melissa37** [comment]
Cool!
M

**Comment by Melissa37** [comment]
Closing. Not on HW anymore and sorted.
No complaints
