### ISSUE TITLE
Schema version 4.3.2 change to 4.3.5 for PoA deposits

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#42]
Would it be ok if POA crossref deposits we change from crossref schema version 4.3.2 to 4.3.4 ? E.g. in this file https://github.com/elifesciences/elife-crossref-feed/blob/poa-crossref/2050-084X_2013_elife01856.xml

**Comment by Melissa37** [comment]
Yes, we should deffo update both PoA and VoR if we change schema.
Just need to get them to both validate locally :-)
Cheers
M

**Comment by gnott** [comment]
Changing to target schema version 4.3.5. POA deposits test is working and valid.

**Comment by Melissa37** [comment]
Great, thanks was quick!
To deploy then close the issue?
Thanks
M

**Comment by Melissa37** [comment]
Yeah!
