### ISSUE TITLE
Set journal_volume based on the article date

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#43]
Currently generate crossref, in the POA v1 only configuration, sets the journal volume by a hardcoded value.

It is better to generate the volume number based on the article's published date.

E.g. Pub date year of 2015 = volume 4

**Comment by Melissa37** [comment]
Yup, that sounds good. As long as there is no change an updated date is used for the volume setting date :-)

**Comment by Melissa37** [comment]
Hi Graham, as we're getting to year end, and doing VoRs too, should we implement this?

**Comment by gnott** [comment]
Right now, if the article XML has a volume then that is used in the deposit. If there is no volume, then we have "4" hard-coded.

We could improve upon the hard-coded "4", to calculate the volume from the pub date year. This would automatically switch over to "5" for PoA articles in the new year.

**Comment by Melissa37** [comment]
Ah OK! So do you think for PoA we need to add this into a sprint before end of Dec?

**Comment by gnott** [comment]
This is easy given we already have a year -> volume calculation elsewhere. So yes, I say do before end of December.

**Comment by Melissa37** [comment]
Done
