### ISSUE TITLE
CrossMark TNQ procedures

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#44]
This is what TNQ do for other publishers:

·         The article metadata file will provide us the inclusion(YES/NO) of the CrossMark information for an article.

·         The XMP metadata containing the Title, Author and Subject will be generated by us and embedded during the PDF creation process of the article. I have attached a sample PDF to show this embedded metadata.

·         The CrossMark logo will be inserted in the first page of the article PDF and hyperlinked to the CrossMark site to check for updates and verify authenticity.

![embedded pdf properties 1](https://cloud.githubusercontent.com/assets/6051876/6785032/1c675c9c-d17b-11e4-9359-4571e2ded858.jpg)

**Comment by Melissa37** [comment]
Do you want to add any other data XMP to the PDF file?

**Comment by Melissa37** [comment]
I also wonder whether we could add it rather than TNQ?

**Comment by Melissa37** [comment]
Also, this is an example of xmp from CrossMark, which seems very expanded to what TNQ are doing now!

http://psychoceramics.labs.crossref.org/site/example1/article_a.xmp

<?xpacket begin="?" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.0-c316 44.253921, Sun Oct 01 2006 17:14:39">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:pdfx="http://ns.adobe.com/pdfx/1.3/" xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/" xmlns:xap="http://ns.adobe.com/xap/1.0/" xmlns:xapRights="http://ns.adobe.com/xap/1.0/rights/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:prism="http://prismstandard.org/namespaces/basic/2.0/" xmlns:crossmark="http://crossref.org/crossmark/1.0/">
<rdf:Description rdf:about="">
<dc:identifier>doi:10.5555/12345678</dc:identifier>
<prism:doi>10.5555/12345678</prism:doi>
<prism:url>http://dx.doi.org/10.5555/12345678</prism:url>
<crossmark:MajorVersionDate>2008-08-14</crossmark:MajorVersionDate>
<crossmark:CrossmarkDomainExclusive>false</crossmark:CrossmarkDomainExclusive>
<crossmark:DOI>10.5555/12345678</crossmark:DOI>
<crossmark:CrossMarkDomains>
<rdf:Seq>
<rdf:li>psychoceramics.labs.crossref.org</rdf:li>
</rdf:Seq>
</crossmark:CrossMarkDomains>
<pdfx:doi>10.5555/12345678</pdfx:doi>
<pdfx:CrossmarkMajorVersionDate>2008-08-14</pdfx:CrossmarkMajorVersionDate>
<pdfx:CrossmarkDomainExclusive>false</pdfx:CrossmarkDomainExclusive>
<pdfx:CrossMarkDomains>
<rdf:Seq>
<rdf:li>psychoceramics.labs.crossref.org</rdf:li>
</rdf:Seq>
</pdfx:CrossMarkDomains>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>

**Comment by Melissa37** [comment]
The technology team informed me that it will take 7 working days to implement  this in the Live articles.
 
Also for the archive articles(includes all the article types and around 1000 articles) we need to insert this XMP metadata and CrossMark logo manually in each article’s PDF. This would consume around 20-30mins per article.

I think we should automate this and do ourselves. Plan to join CrossMark after the planned work and once things are settled - in Q4 2015.

**Comment by gnott** [comment]
Results of first discussion: 

We could use https://github.com/CrossRef/pdfstamp to add the logo.

To add XMP data, https://github.com/CrossRef/pdfmark, but I think by default the data it adds it taken directly from Crossref's data. If the data to add differs or is not yet available in Crossref's version of the data, then it should be fed data from our parser.

Updating the archive would use an approach similar to what was done in converting NLM to JATS - elife-bot assisted workflow: download the PDF zip file, unzip, stamp, mark, rezip, upload to S3 to replace the old PDF.

**Comment by Melissa37** [comment]
Hi there

Sounds great! 
We could deliver to CrossRef then stamp and XMP the files, but there can be a delay at CrossRef and I would not want to delay publication, so would be better to go down the Parser route.

Incidentally, by doing CrossMark ourselves, we'll be putting a step into the process between vendor delivery and delivery to "online host", so we'd need to make sure this would action could happen on an every 15 min basis to not delay publication.

Also, as we deliver CrossRef xml from our processes, again that needs to be done on a regular basis to ensure DOIs are registered pre-publication.

**Comment by Melissa37** [comment]
Not doing, never did.
