### ISSUE TITLE
add different license information to deposits (for figures not CCBY)

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#63]
https://elifesciences.atlassian.net/browse/ELPP-916?filter=-1

**Comment by gnott** [comment]
I'm looking at this again. So far with the data in the new kitchen sink and also another example in the new code repo which is 02020 (has a component with an alternate license / permission). Both of these are not suitable if trying to use https://data.crossref.org/schemas/AccessIndicators.xsd ``<ai:license_ref>`` tag, because it will only accept URL formats. Neither of these example articles have a URL for the license, just a sentence.

**Comment by Melissa37** [comment]
The Crossref support thread does not cover your issue about a url. I have created a follow up question to them and will report their response here. I said:
I'm looking at this again. If trying to use https://data.crossref.org/schemas/AccessIndicators.xsd <ai:license_ref> tag, it will only accept URL formats. 
Where we have a different license for a figure or table, it's usually because it is not a creative commons license and so is something like "All rights reserved". 
Could you change this so it does not have to be a url?

**Comment by Melissa37** [comment]
The old Crossref thread was me trying to get it to work with a url:
The <ai:program> section should appear directly above the <doi_data> section.

**Comment by Melissa37** [comment]
Pulling it all together here, I have followed up on that ticket with this:

We have had this discussion before (I cannot find it in zendesk but found it in eLife's JIRA:

17/May/16 10:58 AM 
The issue of license_ref values be a URL to a license is a bit of a problem as the reason we need to hook out these sub-DOIs is because they are not CC-BY and do not have a specific license, and this needs to be indicated. This will affect text and data mining when we join up. 
Would the suggestion be that eLife creates a url to put into these specific fields and this leads to a page indicating that items are not CC-BY? 
How are other publishers dealing with this requirement? Or is our use-case so unique? 
From CrossRef: 
Response from CrossRef: Patricia Feeney (CrossRef Support) 
Aug 26, 16:57 
Hi Melissa, 
That's a good question! I think that linking to a page as you describe is appropriate, I am cc'ing Rachael as she might have more insight into how other publishers handle this situation. 
-Patricia

----- 
Was this every resolved? We are working on our crossfef submission tool right now, so need to decide how to deal with it and whether to build a website page we refer to for TDM purposes.

Cheers!

M

**Comment by Melissa37** [comment]
Have also contacted editorial to see whether we can pop a bit in the author guide that can be used as this url

**Comment by Melissa37** [comment]
Melissa to provide the url

**Comment by Melissa37** [comment]
@sianroderick 

Hannah is trying to create an anchor to "Copyrighted Material" in this page:

https://submit.elifesciences.org/html/elife_author_instructions.html#policies

Nick is timed out and cannot help her and she cannot work it out. 
This item is blocked on this.
Can someone in the dev team help? Or even @gnott how about you?

Thanks!
M

**Comment by sianroderick** [comment]
Hannah D will send some details/files over and I'll ask David to take a look.

**Comment by Melissa37** [comment]
Thanks!

**Comment by Melissa37** [comment]
Currently blocked by EJP providing info to Hannah

**Comment by Melissa37** [comment]
wehey, here is the url:

The link <https://submit.elifesciences.org/html/elife_author_instructions.html#copyrightedMaterial> will now take the visitor to this section of the Author guide.

**Comment by gnott** [comment]
Thanks Melissa. I have a valid logic to add the value. It requires 

1) a component to have a copyright statement or license value on it, and 
2) in the journal's configuration to have a value specified in the ``component_license_ref`` attribute, which by default will be blank

The above logic will produce the following Crossref XML for eLife article 02020, for example, the new part being the ``<ai:program>`` tag part

```
<component parent_relation="isPartOf">
<titles>
<title>
Figure 6. Class priority of diagnostic classifications for images.
</title>
<subtitle>
The full computer vision algorithm and Clinical Face Phenotype Space analysis procedure with diagnostic hypothesis generation exemplified by: (A) a patient (Ferrero et al., 2007) with Williams-Beuren. (B) Abraham Lincoln. The former US President is thought to have had a marfanoid disorder, if not Marfan syndrome (Gordon, 1962; Sotos, 2012). Bar graphs show class prioritization of diagnostic hypotheses determined by 20 nearest neighbors weighted by prevalence in the database. As expected, the classification of Marfan is not successfully assigned in the first instance as there were only 18 faces of individuals with Marfan in the database (making this an example of a difficult case with the current database). However, the seventh suggestion is Marfan, despite this being among 90 different syndromes and 2754 faces.
</subtitle>
</titles>
<format mime_type="image/tiff"/>
<ai:program name="AccessIndicators">
<ai:license_ref>
https://submit.elifesciences.org/html/elife_author_instructions.html#policies
</ai:license_ref>
</ai:program>
<doi_data>
<doi>10.7554/eLife.02020.017</doi>
<resource>https://elifesciences.org/articles/02020#fig6</resource>
</doi_data>
</component>
```

**Comment by Melissa37** [comment]
Fantastic, thanks!
M

**Comment by gnott** [comment]
Thanks for looking Melissa, I will merge it in now. It will get deployed at the next deployment juncture.
