### ISSUE TITLE
CrossRef update: <ai:program name="AccessIndicators">

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#64]
https://elifesciences.atlassian.net/browse/ELPP-914?filter=-1

**Comment by Melissa37** [comment]
See http://browse.crossref.org/members/4374

Only approx 30% of content has links.

**Comment by Melissa37** [comment]
We'll deal with article main level DOI - PDF/XML/Webpage

Will not deal with sub article DOIs

**Comment by Melissa37** [comment]
@sianroderick Can we have a chat +/- relevant people from your team and Graham about this

Graham needs to explain how people will be directed to the HTML/XML/PDF versions of main DOIs

I was going down a rabbit hole of thinking we should provide links to all the assets in the Crossref service, but stepping outta that hole I think that is overkill and not what the service is designed for anyhow.
However, would like this all sense checked by Dev team :-)

**Comment by sianroderick** [comment]
Of course - I'll leave you to find a slot that suits you.  (Ditto for https://github.com/elifesciences/elife-crossref-feed/issues/76)

**Comment by Melissa37** [comment]
Re https://elifesciences.atlassian.net/browse/ELPP-914

We'll provide Crossref with urls to sub article DOIs that are links to anchors in the html page. See  #76. 
For their <ai:program name="AccessIndicators"> program we'll provide three uris for each article:

1. link to html page (eLife website)
2. link to PDF (via elife website)
3. link to XML (via CDN)

@gnott I have not checked the Crossref schema to check we can add three uri/urls but I assume we can!
We'll need to redeposit the archive updated - we've already been told by Crossref that some of our AccessIndicators are wrong, so need correcting.

**Comment by gnott** [comment]
Based on the article https://support.crossref.org/hc/en-us/articles/214298866, I see there are two additional  data we can provide: the URL of the XML file, and the URL of the PDF. The standard URL which has no particular mime_type associated with it I believe is to be assumed as the HTML version of the article (the default we already provide).
