### ISSUE TITLE
Write list of stages of build eLife article (eg authors, abstract etc)

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#67]

**Comment by gnott** [comment]
Also for possible custom configurations via settings.

**Comment by Melissa37** [comment]
https://github.com/elifesciences/elife-article/blob/develop/elifearticle/article.py

**Comment by gnott** [comment]
I think these stages are actually in https://github.com/elifesciences/elife-article/blob/develop/elifearticle/parse.py  (if we can discuss to be sure we've completed this issue, I can't remember its significance)

The stages stem from:

```
build_article_from_xml()
```
which builds using these functions
```
build_related_articles()
build_contributors()
build_funding()
build_ref_list()
build_components()
```

**Comment by gnott** [comment]
But, in https://github.com/elifesciences/elife-article/blob/develop/elifearticle/article.py  there are objects that are article parts. For example, ``Dataset`` is used when generating PoA XML, but it is not used in CrossRef and PubMed deposits (that uses ``parse.py`` to build an object first).

As in the previous comment, I'm not sure the significance of this list in the article object repository. We may have been discussing the stages of when PoA XML is generated, which will come later.
