### ISSUE TITLE
Build tests and refactor existing tests

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#71]
eLife XML and other XML and edge cases
to check the input matches the output
Extend tests so not just passing for a few edge case articles
Tests are written in Python

**Comment by gnott** [comment]
Existing tests to parse XML into an article object are copied over, which provides the 100% parsing test coverage.

Some additional checking of the attributes of eLife article 02935 are added.

I would like to add some more detailed tests parsing the new kitchen sink 00666 XML file.

**Comment by gnott** [comment]
Added parsing the 00666 kitchen sink and some tests now.
