### ISSUE TITLE
Make tests built automatically

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#73]

**Comment by gnott** [comment]
@giorgiosironi, when time allows, is this new repo something that Alfred can build? It will be a library.

**Comment by giorgiosironi** [comment]
Yes, it seems not to be difficult as it's a Python library similar to elife-tools. Will open a PR with the necessary support.

**Comment by giorgiosironi** [comment]
The build is running at https://ci--alfred.elifesciences.org/job/library-elife-article/1/console but it needs a coveralls token for this project to complete. Can you send me one somewhere private?
