### ISSUE TITLE
Only import Crossref allowed data

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#75]
Does not pull in items in object that are not deposited to Crossref

**Comment by gnott** [comment]
Option for a publisher to customise the data that is included in the crossref deposit.

**Comment by gnott** [comment]
Build parts are configurable now, the ones we need to build include

```
['abstract', 'basic', 'components', 'contributors', 'funding',
        'license', 'pub_dates', 'references', 'volume']
```

**Comment by gnott** [comment]
Also, contributor details to be built can be "brief" rather than "full", which was previously the default.

I'm not sure these options made it any faster or whether it added much advantage yet.
