### ISSUE TITLE
Redeposit all DOIs with direct URLs

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#76]

**Comment by Melissa37** [comment]
@sianroderick when do you think we should do this?

**Comment by sianroderick** [comment]
I think we can avoid doing this as we retained the lookup/doi links in the end (but perhaps we should chat in person to make sure I'm not missing something).

**Comment by Melissa37** [comment]
This is now more about being good Crossref citizens and aiding their efforts to mine the data linking - fewer redirects help.

**Comment by sianroderick** [comment]
Got it.  That makes sense - thanks for the context.

**Comment by gnott** [comment]
As part of https://github.com/elifesciences/elife-crossref-xml-generation/pull/18, I've added some additional traits that can be used in the DOI URLs. 

Before there was only ``{doi}``, which is how the standard lookup URL values was functioning (and is in use by other publishers too, I believe).

Added are some additional attributes that can be used in the DOI URL pattern: ``{manuscript}``, ``{id}`` (for component DOIs), and ``{prefix1}`` -- a URL prefix so in eLife's case some DOI URLs the user should visit the "Figures and data" tab to reach the particular component.

``{prefix1}`` could be set differently by different publishers, perhaps, or they could also have a custom resource URL function to also add their custom logic as eLife has done.

**Comment by Melissa37** [comment]
@sianroderick Can we have a chat +/- relevant people from your team and Graham about this

Summary from me (as I understand it all!):
Graham has come up with some logic for urls for direct links for DOI deposits, which include anchors for the sub-Article DOIs
He can create a list of the urls that will be produced - can auto-check for patterns
Don't want to check the whole list, but that should be sufficient.
We can redeposit everything to Crossref very easily

**Comment by Melissa37** [comment]
This remains the plan.

**Comment by gnott** [comment]
I will close this, being done or ready via the current configuration.
