### ISSUE TITLE
Add "facemark up" to titles

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#87]
https://support.crossref.org/hc/en-us/articles/214532023

The Crossref schema supports minimal face markup in order to avoid ambiguity in certain disciplines (e.g. Genetics, where the same text may be a gene (when italicized) or a protein (when not italicized).

Face markup that appears in the title, subtitle, original_language_title, and unstructured_citation elements should be retained when depositing metadata. Face markup in other elements (e.g. small caps in author names) must be dropped. Face markup support includes bold (b), italic (i), underline (u), over-line (ovl), superscript (sup), subscript (sub), small caps (scp), and typewriter text (tt).

Examples where inclusion of face markup is especially important include:

Italic in titles for terms such as species names or genes
Super and subscript in titles as part of chemical names (e.g. H20)
Super and subscript in simple inline mathematics (e.g. x2 + y2 = z2)
The schema supports nested face markup (e.g. "This text is bold and italic"), which would be tagged as:

This text is <b><i>bold and italic</i></b>

Correspondingly, super and subscript may be nested for correct representation of xyz. This expression should be tagged as:

x<sup>y<sup>z</sup></sup>

**Comment by gnott** [comment]
It looks like the code already generated inline tags of these type in the journal_article ``<title>`` element.

I was hoping these tags would also be available for the citation ``<article_title>`` - after trying I see the schema will not allow it here.

I also stripped tags from an author name (an organisation) that had italics, since these inline tags are also not allowed in the citation ``<author>`` tag.

**Comment by Melissa37** [comment]
HI @gnott 

From Crossref: The markup is stripped out of the API JSON output unfortunately.  

So, there's no point adding it because the use case if for our mark up to show up when other people collect reference data from the Crossref API!

I am going to close this issue.

M
