### ISSUE TITLE
citation comment field content

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-crossref-feed#88]
Is there a Crossref schema field in which we can put citation comment? In one example, this gets converted to an ``<unstructured_citation>``.

JATS

```
<ref id="B26">
<label>26</label>
<element-citation publication-type="webpage">
<person-group person-group-type="author">
<collab>Minnesota State Fair</collab>
</person-group>
<article-title>Minnesota state fair website</article-title>
<year iso-8601-date="2015">2015</year>
<comment>
Available at:
<uri>http://www.mnstatefair.org/</uri>
[Last Accessed 27 July 2016]
</comment>
</element-citation>
</ref>
```

Crossref XML

```
<citation key="key20170704071838_B26">
<unstructured_citation>
Minnesota State Fair
Minnesota state fair website2015Available at: http://www.mnstatefair.org/ [Last Accessed 27 July 2016]
</unstructured_citation>
```

**Comment by Melissa37** [comment]
Ah, I think this would need to be converted to unstructured.

**Comment by Melissa37** [comment]
For eLife - can ignore Comment and keep structured
For generic - do not ignore but convert to unstructured

**Comment by gnott** [comment]
Maybe all citations of type ``publication-type="webpage"`` should be converted to unstructured_citation anyway, since it probably does not have a DOI or ISBN? I think unstructured_citation is the only place we can put a web address anyway.

**Comment by Melissa37** [comment]
Yes, this was issue https://github.com/elifesciences/elife-crossref-feed/issues/98 which you closed a few days ago? Websites should be converted to unstructred
