### ISSUE TITLE
Converting Major datasets to relation

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#92]
Datasets generated by the paper need to be converted to relationship-type="isSupplementedBy" and for those datasets previously published the  relationship-type="references"

```xml
<program xmlns="http://www.crossref.org/relations.xsd">
  <related_item>
    <description>NKX2-5 mutations causative for congenital heart disease retain and are directed to hundreds of targets</description>
    <inter_work_relation relationship-type="**isSupplementedBy**" identifier-type="Accession">GSE44902</inter_work_relation>
  </related_item>
</program>
```

We need to do some analysis on the archive and may need to change the tagging of our XML or do some magic on the bot side of things.

We put a url in the tagging unless there is a DOI and we think it is only then that  a pub-id is used.
The kitchen sink is not good examples of this because I've used Github and Dryad as examples, not what our authors tend to use.

For accession numbers you can derive it from the url string. 
Will probably require some thoughtful input. 
Am including @JGilbert-eLife and @thewilkybarkid

**Comment by gnott** [comment]
In kitchen sink article JATS XML, from the dataset ``<related-object>`` we are often parsing details that are available including: authors, source/title, year/date, comment.

@Melissa37 what is the best combination of these elements to use in the Crossref description field for the related_item associated with a dataset?

**Comment by Melissa37** [comment]
Please use the data set title as the <description>
and the identifier as identifier-type=""
This might be a url for lots of them

**Comment by gnott** [comment]
Great, thanks Melissa. I will mark this issue as done then since it is doing the above now.
