### ISSUE TITLE
Provide  iso-8601-date and not date provided for display

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#93]
For example, this:

```xml
 <year iso-8601-date="2004">2004a</year>
```

Is getting converted to 
```xml
  <cYear>2004b</cYear>
```

The a,b,c values mean nothing to Crossref and serve no purpose in this context and they create unclean data. They want just the date, so we should use the iso-8601-date value instead

**Comment by gnott** [comment]
In the case above, it will prefer the numeric value for year taken from the ``iso-8601-date`` attribute, or if that is not available then it will use the date text as written, e.g. ``2004b``.
