### ISSUE TITLE
Book references at the chapter level

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#95]
Example of a reference to a chapter in a book:

```xml
<ref id="bib11">
        <element-citation publication-type="book">
            <person-group person-group-type="author">
                <name>
                    <surname>Coyne</surname>
                    <given-names>JA</given-names>
                </name>
                <name>
                    <surname>Orr</surname>
                    <given-names>HA</given-names>
                </name>
            </person-group>
            <person-group person-group-type="editor">
                <name>
                    <surname>Otte</surname>
                    <given-names>D</given-names>
                </name>
                <name>
                    <surname>Endler</surname>
                    <given-names>JA</given-names>
                </name>
            </person-group>
            <year iso-8601-date="1989">1989</year>
            <chapter-title>Two rules of speciation</chapter-title>
            <source>Speciation and its consequences</source>
            <fpage>1</fpage>
            <lpage>2</lpage>
            <publisher-loc>Sunderland, MA</publisher-loc>
            <publisher-name>Sinauer Associates</publisher-name>
        </element-citation>
    </ref>
```
Gets converted to:

```xml
<citation key="11">
                        <volume_title>Speciation and its consequences</volume_title>
                        <author>Coyne</author>
                        <first_page>1</first_page>
                        <cYear>1989</cYear>
                    </citation>
```

@gnott can you confirm it is selecting the first author surname in the person group with a type "author" instead of the first author of the first person group?

Just in case the vendors ever supply the wrong way round. This is what Crossref want:

"If a citation cites a book at the chapter level, the metadata should be included as much as possible - including fpage and author of the chapter as opposed to the book (if they differ). "

**Comment by gnott** [comment]
I will write a test for this. Early investigations now I do not think the ``person-group-type`` gets included as it flows through, and the order would matter. Good suggestion, and it is a perfect time to add this detail.

**Comment by gnott** [comment]
The value is retained now (as ``group-type`` for the ref author in python code), and the first draft seems to work as expected. The unexpected result is the following one example of a reference in the 00666 kitchen sink has no authors, so the author is omitted in the Crossref deposit:

```
<ref id="bib8">
<element-citation publication-type="book">
<person-group person-group-type="editor">
<name>
<surname>Cardé</surname>
<given-names>RT</given-names>
</name>
<name>
<surname>Millar</surname>
<given-names>JG</given-names>
</name>
</person-group>
<year iso-8601-date="2004">2004</year>
<source>Advances in insect chemical ecology</source>
<publisher-name>Cambridge University Press</publisher-name>
<publisher-loc>Cambridge</publisher-loc>
</element-citation>
</ref>
```

Omitting an ``<author>`` in the deposit seems to be valid in the Crossref schema. Is that the desired option, to not include an author at all?

I will continue with this logic; in reviewing the common4.3.5.xsd schema, there is no field called ``editor`` for ``citation``, so there doesn't seem to be a place for it, so the citation will have no author.

**Comment by Melissa37** [comment]
Ah sorry for the confusion. The logic is:

If there is an author group and an editor group, take the first author of the author group.
If there is only an editor group, take the first author of the editor group.

Does that make sense?

**Comment by gnott** [comment]
I am adding logic to use the editors if no authors are available as the default for all citations. 

Now there is a new ``filter_citation_authors()`` function, it is possible to additionally make the citation author filtering to be customised based on the citation type (book, patent, etc.) in the future, including for when the unstructured_citation author line is concatenated.
