### ISSUE TITLE
General info: converting to unstructured citation - Crossref feedback

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#99]
MH: Patent/Clinical Trials/Reports/Conference proceedings/websites/software/Theses - what we provide will be next to useless as it does not fit into the schema, so would it be more useful to convert to an unstructured citation, then we could add the url, for instance, which I see as the most useful piece of information when their is no PID.

Crossref: Yes, that's the best approach - we don't currently index URLs for citation matching but may incorporate that into reference parsing in the future.

**Comment by gnott** [comment]
I think I've mentioned it before, though I'm not sure if ``<unstructured_citation>`` tags should be the only tag in a citation, or whether it as well as other citation tags can be included together. Including them all together is not invalid against the Crossref schema. @Melissa37 do you know if there is a particular preference regarding the unstructured_citation tag?

**Comment by gnott** [comment]
There's one example on https://support.crossref.org/hc/en-us/articles/213123706-Journals-and-journal-articles  where the citations with ``<unstructured_citation>`` tags have only the ``<unstructured_citation>`` tag. This is some indication of how the deposits should be, but it would be good if we are more sure about it.

**Comment by Melissa37** [comment]
Are you referring to this:

```
xml
<citation key="key-10.9876/S0003695199034166-14">
<unstructured_citation>
L. Reynolds, Three dimensional reflection and transmission equations for optical diffusion in blood, MS Thesis. Seattle, Washington: University of Washington (1970).
</unstructured_citation>
</citation>
<citation key="key-10.9876/S0003695199034166-15">
<unstructured_citation>
T. J. Dresse, U.S. Patent 308, 389 [
<i>CA 82</i>
, 73022 (1975)].
</unstructured_citation>
</citation>
```
?

**Comment by gnott** [comment]
I think in issue https://github.com/elifesciences/elife-crossref-feed/issues/116  I think you illustrated my primary question about ``<unstructured_citation>``, and possibly the only remaining question. As an example the question is which of the below examples is preferred by Crossref?

1. All the tags
```
<citation key="12">
<volume_title>PyMol</volume_title>
<author>DeLano</author>
<cYear>2002</cYear>
<article_title>The PyMol Molecular Graphics System</article_title>
<unstructured_citation>DeLano W. 2002. The PyMol Molecular Graphics System.                            Schrödinger LLC. PyMol. Version 1.7.4. https://www.pymol.org/.</unstructured_citation>
</citation>
```

2. Only the unstructured_citation tag
```
<citation key="12">
<unstructured_citation>DeLano W. 2002. The PyMol Molecular Graphics System.                            Schrödinger LLC. PyMol. Version 1.7.4. https://www.pymol.org/.</unstructured_citation>
</citation>
```

**Comment by Melissa37** [comment]
Question submitted to Crossref:
https://support.crossref.org/hc/en-us/requests/80989

I prefer 1, but we'll ask them :-)

**Comment by Melissa37** [comment]
From Crossref:

Our system only checks for citation matches among Crossref DOIs.  We can match non-journal content (books, conferences, etc.), though journal articles do make up the bulk of our metadata records.

**Comment by Melissa37** [comment]
So we'll go for option 1

**Comment by gnott** [comment]
Great, thanks. We're already doing option 1 so let's keep that for now and intend to deploy it as the first go of these unstructured_citation tags.
